#!/usr/bin/env bash
#  Bash script that will display information about subdomains.domain=$1
domain=$1
subdomain=${2}
record_type="$(dig "$domain" | grep -A1 'ANSWER SECTION:' | awk '{print $(NF-1)}' | tail -1)"
if [ $# = 2 ]; then
    # dig "$domain"."$subdomain" | grep -A1 'ANSWER SECTION:'
    destination="$(dig "$domain" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -1)"
    echo "The subdomain ""$subdomain"" is a ""$record_type"" record and points to ""$destination"""

else
    subdomain=("www" "lb-01" "web-01" "web-02" )

    for rec in "${subdomain[@]}"; do
        destination="$(dig "$rec.$domain" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -1)"
        echo "The subdomain ""$rec"" is a ""$record_type"" record and points to ""$destination"""
    done
fi
