#!/usr/bin/env bash
if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

else
    path_file=$1
    ip=$2
    username=$3
    path_ssh=$4

    cp $"path_file" $"ip"
fi