#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.
sudo apt update
sudo apt install -y nginx
echo "Hello World!" > /var/www/html/index.html

sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;}' /etc/nginx/sites-available/default

sudo service nginx start
