#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.
sudo apt update
sudo apt install -y nginx
echo "<p>Hello World!</p>" > /var/www/html/index.html

echo "http{
        server{
            listen 80;
            location /redirect_me {
                return https://www.youtube.com/watch?v=jIQ6UV2onyI&pp=ygUHbnlhIGNhdA%3D%3D
            }
        }
    }"| sudo tee /etc/nginx/sites-available/redirect_me
sudo service nginx start
