#!/usr/bin/env bash
# custom 404 page
sudo apt update
sudo apt install -y nginx
echo "Hello World!" > /var/www/html/index.html

sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;}' /etc/nginx/sites-available/default
sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 404 "Ceci n'\''est pas une page\n";}' /etc/nginx/sites-available/default

sudo service nginx start
