#!/usr/bin/env bash
# custom 404 page
sudo apt update
sudo apt install -y nginx
echo "Hello World!" > /var/www/html/index.html

sudo sed -i 's|location \/redirect_me {|location \/redirect_me { return 301 https:\/\/www.youtube.com\/watch?v=jIQ6UV2onyI\&pp=ygUHbnlhIGNhdA%3D%3D;|' /etc/nginx/sites-available/default
sudo sed -i 's|location \/redirect_me {|location \/redirect_me { return 404 Ceci n'\''est pas une page;|' /etc/nginx/sites-available/default

sudo service nginx start
