#!/usr/bin/env bash
#double the number of webservers
sudo apt update
sudo apt install -y nginx
echo "<p>Hello World!</p>" > /var/www/html/index.html
echo -e "server {\n\tlocation / {\n\t\tadd_header X-Served-By: $HOSTNAME;\n\t}\n}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx start