#!/usr/bin/env bash
#double the number of webservers
sudo apt update
sudo apt install -y nginx
echo "<p>Hello World!</p>" > /var/www/html/index.html
echo -e "add_header X-Served-By $HOSTNAME;\n" | sudo tee /etc/nginx/nginx.conf
sudo service nginx start