#!/usr/bin/env bash
# Nginx likes port 80
sudo apt update
sudo apt install -y nginx
ufw allow 80
printf "server {\n\tlisten 80 default_server;\n\tlisten [::]:80 default_server;\n}\n"  >  /etc/nginx/nginx.conf
sudo service nginx start