#!/usr/bin/env bash
# This script is displaying "Best School" 10 times (but not 4, 8 time)

i=1
while [ $i -le 20 ]
do
	echo "$i"
	case $i in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
	esac
	((i++))
done
