#!/usr/bin/env bash
#Block all incoming traffic but
sudo apt-get update
sudo apt-get install -y ufw
sudo ufw default deny incoming
sudo ufw enable
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
