#!/usr/bin/env bash
# Script that make Apache  run on the container and return a page containing Hello Holberto
# docker exec -ti "$(docker ps -q)" /bin/bash -c "apt-get update && apt-get install -y apache2;service apache2 start; echo "Hello Holberton" > /var/www/html/index.html ; exit"
sudo service apache2 start