#!/usr/bin/env bash
# Nginx configuration
config="server{
    listen: 80,
    server_name 127.0.0.1
    location /airbnb-onepage/ {
        proxy_pass http://127.0.0.1:5000;
    }

}"
echo "$config" > /etc/nginx/sites-available/default
